package com.pentaware.doorish.model;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class Dashboard implements Serializable {

    public List<String> best_selling_products = new ArrayList<>();
    public List<String> deals_of_the_day = new ArrayList<>();
    public List<String> flat_50_off = new ArrayList<>();
    public List<String> lowest_price = new ArrayList<>();
    public List<String> new_arrivals = new ArrayList<>();

    public List<String> grp_1_top_picks = new ArrayList<>();
    public List<String> grp_2_top_picks = new ArrayList<>();
    public List<String> grp_3_top_picks = new ArrayList<>();
    public List<String> grp_4_top_picks = new ArrayList<>();
    public List<String> grp_5_top_picks = new ArrayList<>();
    public List<String> grp_6_top_picks = new ArrayList<>();
    public List<String> grp_7_top_picks = new ArrayList<>();
    public List<String> grp_8_top_picks = new ArrayList<>();
    public List<String> grp_9_top_picks = new ArrayList<>();
    public List<String> grp_10_top_picks = new ArrayList<>();
    public List<String> grp_11_top_picks = new ArrayList<>();
    public List<String> grp_12_top_picks = new ArrayList<>();


    public String carousel_img1_tag;
    public String carousel_img2_tag;
    public String carousel_img3_tag;
    public String carousel_img4_tag;
    public String carousel_img5_tag;
    public String carousel_img1_url;
    public String carousel_img2_url;
    public String carousel_img3_url;
    public String carousel_img4_url;
    public String carousel_img5_url;

    public String featured_img1_tag;
    public String featured_img2_tag;
    public String featured_img3_tag;
    public String featured_img4_tag;
    public String featured_img5_tag;
    public String featured_img6_tag;
    public String featured_img7_tag;
    public String featured_img8_tag;
    public String featured_img9_tag;
    public String featured_img10_tag;
    public String featured_img11_tag;
    public String featured_img12_tag;


    public String featured_img1_url;
    public String featured_img2_url;
    public String featured_img3_url;
    public String featured_img4_url;
    public String featured_img5_url;
    public String featured_img6_url;
    public String featured_img7_url;
    public String featured_img8_url;
    public String featured_img9_url;
    public String featured_img10_url;
    public String featured_img11_url;
    public String featured_img12_url;

    public String grp1_Title;
    public String grp1_img1_tag;
    public String grp1_img2_tag;
    public String grp1_img3_tag;
    public String grp1_img4_tag;
    public String grp1_img1_name;
    public String grp1_img2_name;
    public String grp1_img3_name;
    public String grp1_img4_name;
    public int discount_grp1_img1;
    public int discount_grp1_img2;
    public int discount_grp1_img3;
    public int discount_grp1_img4;
    public String grp1_img1_url;
    public String grp1_img2_url;
    public String grp1_img3_url;
    public String grp1_img4_url;

    public String grp2_Title;
    public String grp2_img1_tag;
    public String grp2_img2_tag;
    public String grp2_img3_tag;
    public String grp2_img4_tag;
    public String grp2_img1_name;
    public String grp2_img2_name;
    public String grp2_img3_name;
    public String grp2_img4_name;
    public int discount_grp2_img1;
    public int discount_grp2_img2;
    public int discount_grp2_img3;
    public int discount_grp2_img4;
    public String grp2_img1_url;
    public String grp2_img2_url;
    public String grp2_img3_url;
    public String grp2_img4_url;

    public String grp3_Title;
    public String grp3_img1_tag;
    public String grp3_img2_tag;
    public String grp3_img3_tag;
    public String grp3_img4_tag;
    public String grp3_img1_name;
    public String grp3_img2_name;
    public String grp3_img3_name;
    public String grp3_img4_name;
    public int discount_grp3_img1;
    public int discount_grp3_img2;
    public int discount_grp3_img3;
    public int discount_grp3_img4;
    public String grp3_img1_url;
    public String grp3_img2_url;
    public String grp3_img3_url;
    public String grp3_img4_url;

    public String grp4_Title;
    public String grp4_img1_tag;
    public String grp4_img2_tag;
    public String grp4_img3_tag;
    public String grp4_img4_tag;
    public String grp4_img1_name;
    public String grp4_img2_name;
    public String grp4_img3_name;
    public String grp4_img4_name;
    public int discount_grp4_img1;
    public int discount_grp4_img2;
    public int discount_grp4_img3;
    public int discount_grp4_img4;
    public String grp4_img1_url;
    public String grp4_img2_url;
    public String grp4_img3_url;
    public String grp4_img4_url;

    public String grp5_Title;
    public String grp5_img1_tag;
    public String grp5_img2_tag;
    public String grp5_img3_tag;
    public String grp5_img4_tag;
    public String grp5_img1_name;
    public String grp5_img2_name;
    public String grp5_img3_name;
    public String grp5_img4_name;
    public int discount_grp5_img1;
    public int discount_grp5_img2;
    public int discount_grp5_img3;
    public int discount_grp5_img4;
    public String grp5_img1_url;
    public String grp5_img2_url;
    public String grp5_img3_url;
    public String grp5_img4_url;

    public String grp6_Title;
    public String grp6_img1_tag;
    public String grp6_img2_tag;
    public String grp6_img3_tag;
    public String grp6_img4_tag;
    public String grp6_img1_name;
    public String grp6_img2_name;
    public String grp6_img3_name;
    public String grp6_img4_name;
    public int discount_grp6_img1;
    public int discount_grp6_img2;
    public int discount_grp6_img3;
    public int discount_grp6_img4;
    public String grp6_img1_url;
    public String grp6_img2_url;
    public String grp6_img3_url;
    public String grp6_img4_url;

    public String grp7_Title;
    public String grp7_img1_tag;
    public String grp7_img2_tag;
    public String grp7_img3_tag;
    public String grp7_img4_tag;
    public String grp7_img1_name;
    public String grp7_img2_name;
    public String grp7_img3_name;
    public String grp7_img4_name;
    public int discount_grp7_img1;
    public int discount_grp7_img2;
    public int discount_grp7_img3;
    public int discount_grp7_img4;
    public String grp7_img1_url;
    public String grp7_img2_url;
    public String grp7_img3_url;
    public String grp7_img4_url;

    public String grp8_Title;
    public String grp8_img1_tag;
    public String grp8_img2_tag;
    public String grp8_img3_tag;
    public String grp8_img4_tag;
    public String grp8_img1_name;
    public String grp8_img2_name;
    public String grp8_img3_name;
    public String grp8_img4_name;
    public int discount_grp8_img1;
    public int discount_grp8_img2;
    public int discount_grp8_img3;
    public int discount_grp8_img4;
    public String grp8_img1_url;
    public String grp8_img2_url;
    public String grp8_img3_url;
    public String grp8_img4_url;

    public String grp9_Title;
    public String grp9_img1_tag;
    public String grp9_img2_tag;
    public String grp9_img3_tag;
    public String grp9_img4_tag;
    public String grp9_img1_name;
    public String grp9_img2_name;
    public String grp9_img3_name;
    public String grp9_img4_name;
    public int discount_grp9_img1;
    public int discount_grp9_img2;
    public int discount_grp9_img3;
    public int discount_grp9_img4;
    public String grp9_img1_url;
    public String grp9_img2_url;
    public String grp9_img3_url;
    public String grp9_img4_url;

    public String grp10_Title;
    public String grp10_img1_tag;
    public String grp10_img2_tag;
    public String grp10_img3_tag;
    public String grp10_img4_tag;
    public String grp10_img1_name;
    public String grp10_img2_name;
    public String grp10_img3_name;
    public String grp10_img4_name;
    public int discount_grp10_img1;
    public int discount_grp10_img2;
    public int discount_grp10_img3;
    public int discount_grp10_img4;
    public String grp10_img1_url;
    public String grp10_img2_url;
    public String grp10_img3_url;
    public String grp10_img4_url;

    public String grp11_Title;
    public String grp11_img1_tag;
    public String grp11_img2_tag;
    public String grp11_img3_tag;
    public String grp11_img4_tag;
    public String grp11_img1_name;
    public String grp11_img2_name;
    public String grp11_img3_name;
    public String grp11_img4_name;
    public int discount_grp11_img1;
    public int discount_grp11_img2;
    public int discount_grp11_img3;
    public int discount_grp11_img4;
    public String grp11_img1_url;
    public String grp11_img2_url;
    public String grp11_img3_url;
    public String grp11_img4_url;

    public String grp12_Title;
    public String grp12_img1_tag;
    public String grp12_img2_tag;
    public String grp12_img3_tag;
    public String grp12_img4_tag;
    public String grp12_img1_name;
    public String grp12_img2_name;
    public String grp12_img3_name;
    public String grp12_img4_name;
    public int discount_grp12_img1;
    public int discount_grp12_img2;
    public int discount_grp12_img3;
    public int discount_grp12_img4;
    public String grp12_img1_url;
    public String grp12_img2_url;
    public String grp12_img3_url;
    public String grp12_img4_url;




}
